version: '3'

volumes:
  ht_postgres_data: {}

services:
  fastapi:
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    container_name: ht_fastapi
    restart: always
    depends_on:
      - postgres
    volumes:
     - .:/app
    env_file:
      - ./.envs_example/.fastapi
      - ./.envs_example/.postgres
    ports:
      - "80:80"
    entrypoint: /start-reload.sh

  postgres:
    build:
      dockerfile: ./compose/postgres/Dockerfile
    container_name: ht_postgres
    restart: always
    volumes:
      - ht_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs_example/.postgres
    ports:
      - "5432:5432"
