"""initial

Revision ID: 1b89263ee7b0
Revises:
Create Date: 2025-04-10 09:05:24.803190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b89263ee7b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('reservation_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('table_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_table_id'), 'reservation', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_table_id'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_table('table')
    # ### end Alembic commands ###
